# Generated by Django 5.0.6 on 2024-05-31 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_cartitem_book_alter_cartitem_cart_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='books',
            field=models.ManyToManyField(related_name='books_purchases', through='store.PurchaseItem', to='store.book'),
        ),
    ]
