version: "3.9"
services:
  redis:
    image: redis:latest
    container_name: redis
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_Name}
      - POSTGRES_USER=${DB_User}
      - POSTGRES_PASSWORD=${DB_Pass}
    ports:
      - "5432:5432"
    container_name: postgres_db
    env_file:
      - ./.env
  backend:
    container_name: BookStore_Backend
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/BookStore
      - ./static:/BookStore/static
      - ./media:/BookStore/media
    env_file:
      - ./.env

  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/BookStore/entrypoints/start-celery.sh"]
    volumes:
      - .:/BookStore
    container_name: celery
    depends_on:
      - redis
      - backend
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/BookStore/static
      - ./media:/BookStore/media
    depends_on:
      - backend